global:
  cattle:
    systemDefaultRegistry: ""

cceOperator:
  image:
    repository: cnrancher/cce-operator
    tag: v0.2.2

httpProxy: ""
httpsProxy: ""
noProxy: ""
additionalTrustedCAs: false
## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}
## List of node taints to tolerate (requires Kubernetes >= 1.6)
tolerations: []

## PriorityClassName assigned to deployment.
priorityClassName: ""
